apiVersion: v1
kind: Service
metadata:
  name: {{ include "annotated-maps.fullname" . }}-api
  labels:
    {{- include "annotated-maps.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "annotated-maps.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
