# deploy/helm/annotated-maps/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "annotated-maps.fullname" . }}
  labels:
    {{- include "annotated-maps.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "annotated-maps.fullname" . }}-api
                port: { number: 8000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "annotated-maps.fullname" . }}-web
                port: { number: 80 }
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
