# Generated by Django 5.1.15 on 2026-06-18 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_section_teaser_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appends",
                to="maps.note",
            ),
        ),
    ]
