# Generated by Django 5.1.15 on 2026-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_note_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="created_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="is_seed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
