# Generated by Django 5.1.15 on 2026-06-19 22:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_note_sandbox_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="area",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="path",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
