# Generated by Django 5.1.15 on 2026-06-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_group_options_alter_group_managers"),
        ("maps", "0005_note_area_path"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", False),
                    models.Q(
                        ("area__isnull", True), ("path__isnull", True), ("point__isnull", False)
                    ),
                    models.Q(
                        ("area__isnull", False), ("path__isnull", True), ("point__isnull", True)
                    ),
                    models.Q(
                        ("area__isnull", True), ("path__isnull", False), ("point__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="note_top_level_exactly_one_anchor",
            ),
        ),
    ]
