apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        filterByTraceID: true
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    uid: prom
  - name: Loki
    type: loki
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":\s*"([0-9a-f]+)"'
          datasourceUid: tempo
          url: "$${__value.raw}"
